const sentences = [
  "/imagine The machine does not isolate man from the great problems of nature but plunges him more deeply into them.",
  "/imagine The only limits that exist are the ones you place on yourself.",
  "/imagine I've seen things you people wouldn't believe… All those moments will be lost in time, like tears in rain.",
  "/imagine In my experience, there's no such thing as luck.",
  "/imagine The danger of the past was that men became slaves. The danger of the future is that men may become robots.",
  "/imagine He that breaks a thing to find out what it is has left the path of wisdom.",
  "/imagine If you've created a conscious machine, it's not the history of man. That's the history of gods.",
  "/imagine All we have to decide is what to do with the time that is given to us.",
  "/imagine Even the smallest person can change the course of the future.",
  "/imagine Your scientists were so preoccupied with whether or not they could, they didn't stop to think if they should.",
  "/imagine There is some good in this world, and it's worth fighting for.",
  "/imagine It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change.",
  "/imagine Technology is a useful servant but a dangerous master.",
  "/imagine We don't know if they understand the difference between a weapon and a tool.",
  "/imagine I will not say, do not weep, for not all tears are an evil.",
  "/imagine It is useless to meet revenge with revenge: it will heal nothing.",
  "/imagine War must be, while we defend our lives against a destroyer who would devour all.",
  "/imagine The bonds of friendship are unbreakable, even in the face of the unknown.",
  "/imagine Faithless is he that says farewell when the road darkens.",
  "/imagine I will take the Ring, though I do not know the way.",
  "/imagine In the darkest of times, a glimmer of hope can shine the brightest.",
  "/imagine Sometimes, the greatest adventures begin with a single step into the unknown.",
  "/imagine It's not about the destination; it's about the journey and the friends you make along the way.",
  "/imagine In the face of adversity, courage is the key to unlocking one's true potential.",
  "/imagine The past may define you, but it doesn't have to control your future.",
  "/imagine Love is a force that transcends time and space.",
  "/imagine Life is a puzzle, and every experience is a piece waiting to be fitted into place.",
  "/imagine To find the answers, sometimes you must ask the right questions.",
  "/imagine Embrace the quirks and imperfections that make you unique; they are your superpower.",
  "/imagine In the silence between the notes, you can find the true beauty of music.",
  "/imagine Sometimes, the most unexpected alliances lead to the greatest victories.",
  "/imagine Life is a canvas, and you are the artist. Paint your story with bold strokes and vibrant colors.",
  "/imagine The greatest stories are not told, they are lived.",
  "/imagine Ever have that feeling where you're not sure if you're awake or dreaming?",
  "/imagine Adventure awaits those who dare to dream and take that first step.",
  "/imagine In the end, it's not the years in your life that count, but the life in your years.",
  "/imagine I'm sorry, Dave. I'm afraid I can't do that.",
  "/imagine The future is not set. There is no fate but what we make for ourselves.",
  "/imagine You either die a hero or live long enough to see yourself become the villain.",
  "/imagine The most profound technologies are those that disappear. They weave themselves into everyday life until they are indistinguishable from it.",
]

export default sentences
