const sentences = [
  "/imagine Earths gravity is 9.8 meters per second per second. Period. And Im experiencing more than that. Theres only one possible explanation. Im not on Earth.",
  "/imagine I feel kind of stupid. There's a whole bunch of science I should be doing, right?",
  "/imagine You cant be a hundred percent serious forever.",
  "/imagine I was talking aloud to myself. A habit of the old: they choose the wisest person present to speak to.",
  "/imagine He that breaks a thing to find out what it is has left the path of wisdom.",
  "/imagine It's a dangerous business, Frodo, going out your door.",
  "/imagine All we have to decide is what to do with the time that is given to us.",
  "/imagine Even the smallest person can change the course of the future.",
  "/imagine The world is indeed full of peril, and in it, there are many dark places.",
  "/imagine There is some good in this world, and it's worth fighting for.",
  "/imagine The shadow does not hold sway yet. Not over you and not over me.",
  "/imagine A wizard is never late, nor is he early, he arrives precisely when he means to.",
  "/imagine The world is changed, I feel it in the water, I feel it in the earth, I smell it in the air.",
  "/imagine Home is behind, the world ahead, and there are many paths to tread.",
  "/imagine Go ahead, make my day.",
  "/imagine It is not the strength of the body that counts, but the strength of the spirit.",
  "/imagine I will not say, do not weep, for not all tears are an evil.",
  "/imagine It is useless to meet revenge with revenge: it will heal nothing.",
  "/imagine War must be, while we defend our lives against a destroyer who would devour all.",
  "/imagine Faithless is he that says farewell when the road darkens.",
  "/imagine I will take the Ring, though I do not know the way.",
  "/imagine In the darkest of times, a glimmer of hope can shine the brightest.",
  "/imagine Sometimes, the greatest adventures begin with a single step into the unknown.",
  "/imagine It's not about the destination; it's about the journey and the friends you make along the way.",
  "/imagine In the face of adversity, courage is the key to unlocking one's true potential.",
  "/imagine The past may define you, but it doesn't have to control your future.",
  "/imagine Love is a force that transcends time and space.",
  "/imagine Life is a puzzle, and every experience is a piece waiting to be fitted into place.",
  "/imagine To find the answers, sometimes you must ask the right questions.",
  "/imagine Embrace the quirks and imperfections that make you unique; they are your superpower.",
  "/imagine In the silence between the notes, you can find the true beauty of music.",
  "/imagine The bonds of friendship are unbreakable, even in the face of the unknown.",
  "/imagine Sometimes, the most unexpected alliances lead to the greatest victories.",
  "/imagine Life is a canvas, and you are the artist. Paint your story with bold strokes and vibrant colors.",
  "/imagine The greatest stories are not told, they are lived.",
  "/imagine When you lose your way, look to the stars; they will guide you home.",
  "/imagine Adventure awaits those who dare to dream and take that first step.",
  "/imagine In the end, it's not the years in your life that count, but the life in your years.",
  "/imagine The world is a book, and those who do not travel read only one page.",
  "/imagine Life is a grand adventure, and every day is a new chapter waiting to be written.",
  "/imagine The best way to predict the future is to create it.",
  "/imagine The only limits that exist are the ones you place on yourself.",
  "/imagine Be the change you wish to see in the world.",
  "/imagine You are never too old to set another goal or to dream a new dream.",
]

export default sentences
